### ISSUE TITLE
Kernel Scope and Lifetime API

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-services#40] opened 2015-10-12 20:19 UTC
Make the Kernel more robust and tie its lifetime to the kernel id.

- [x] Fix the race condition on restart
- [x] Better document the lifecycle of the Kernel JavaScript object
- [x] Clear Comms and Futures on restart
- [x] Add auto-reconnect logic for failed WebSocket connections

**Comment by ellisonbg** [comment] 2015-10-12 20:39
I do think that our notion of the Kernel object in JS, that manages the
WebSocket traffic, should be separate than the Kernel Manager, which makes
the REST calls. To me, this suggests that methods like restart belong on
the Kernel Manager not the Kernel.

On Mon, Oct 12, 2015 at 4:19 PM, Steven Silvester <notifications@github.com>
wrote:

> I suggest we re-address a separation of concerns where a kernel object
> itself is only an abstraction around a WebSocket, and have a separate
> Kernel Manager that is responsible for REST API methods and lifecycle
> management of Kernel objects.
>
> The problem is highlighted by a race condition noticed on Travis: when we
> restart the kernel, we do not necessarily know when the kernel is "ready".
> Sending a kernelInfo() request after the REST API restart response will
> garner a response only if the kernel has actually started. Restarting is
> technically creating a new Kernel, it just happens to be implemented as
> reusing the same Websocket address.
>
> ping @ellisonbg <https://github.com/ellisonbg> @jasongrout
> <https://github.com/jasongrout> @minrk <https://github.com/minrk>
> @sccolbert <https://github.com/sccolbert>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter-js-services/issues/40>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment] 2015-10-13 14:24
The Comm objects should also be tied to the lifetime of the WebSocket, and a restart should result in a clean Kernel with no Comms or Futures.  This should be done irrespective of the refactor (note to self).

**Comment by sccolbert** [comment] 2015-10-13 14:28
+1 to the separation

**Comment by minrk** [comment] 2015-10-13 16:04
I'm not sure what the source of the problem could be, but I will dig into it. It should be safe to start sending requests as soon as the outgoing process has stopped, and the restart request shouldn't be replying before this is true, which might be the bug.

If it helps to separate these, that's fine, as long as one thing is maintained: restarting the kernel does not require recreating or reconnecting the client or websockets.

**Comment by minrk** [comment] 2015-10-13 16:37
This in particular:

> Sending a kernelInfo() request after the REST API restart response will garner a response only if the kernel has actually started.

should be "if the kernel has actually **stopped**". Sending requests prior to the new kernel starting should not be a problem. Only if the prior kernel is still running should it be possible for messages to be lost. zmq will happily queue up requests for a peer that isn't there, though.

I've also introduced a delay of 5 seconds between kernel restart and the start of the new process, showing that kernel info requests sent after the initial shutdown, but several seconds before the new process starts does successfully receive a reply when the kernel finally comes up.

**Comment by blink1073** [comment] 2015-10-13 16:42
We had some discussion on this at NYC and came to this conclusion: the Kernel object should be tied to a kernel uuid, not the WebSocket state.  We can view a restart as clearing the internal state of the Kernel object (comm and futures), but preserving the WebSocket connection.  

The changes that need to be made: 
- Fix the race condition on restart (I'll look into this as well @minrk)
- Clear Comms and Futures on restart
- Add auto-reconnect logic for failed WebSocket connections

**Comment by minrk** [comment] 2015-10-13 16:50
@blink1073 all those points make perfect sense, thanks.

> Fix the race condition on restart

After a bit of testing, I think this might be a problem of not chaining promises or some such in the jjs tests somewhere, not necessarily server side. When I write my own tests introducing a major delay server-side, it doesn't seem to be an issue. Have you ever been able to reproduce the problem outside Travis? Sometimes it is hard to make a real computer as slow as a Travis VM, which is often the source of our async test failures, which can be bugs in tests as often as not.

[my test script](https://gist.github.com/e7021ecfa83771035060), run from the jupyter-js-services repo.

**Comment by blink1073** [comment] 2015-10-13 16:56
@minrk, I have not seen any failures on my local machine.  I had debated whether to add an artificial delay on Travis to accommodate the slowness.  I think the right solution is to force-send a `restarting` iopub message after the kernel process stops.

**Comment by sccolbert** [comment] 2015-10-13 16:58
The correctness of tests and APIs should not depend on the speed of the machine.

**Comment by blink1073** [comment] 2015-10-13 22:04
I think `starting` should be the event we are looking for, since that is emitted by the kernel at process startup.  However this [build](https://travis-ci.org/blink1073/jupyter-js-services/builds/85214720) demonstrates a build where the Kernel spec is in compliance, but this [build](https://travis-ci.org/blink1073/jupyter-js-services/builds/85210392) demonstrates where we have an open WebSocket connection, but no `starting` message is received.

**Comment by minrk** [comment] 2015-10-14 09:04
Thanks for tracking it down, I think I know what's up. It's probably a zmq subscription issue. The 'starting' message coming from the kernel could be sent before the subscribing peer has established its subscriptions. I'm not entirely sure why the starting message was added, since it's done at an unreliable time, and entirely redundant. There isn't a reason to wait for this event.

On the jjs side, the fix is probably that the restart promise should resolve as soon as the AJAX reply arrives, and not watch for any status events. On the server-side, we can consider making changes that ensure the kernel has become responsive (by pinging with kernel_info) before resolving the restart request.

**Closed** 2015-10-27 12:15 UTC
